tellraw @s {"rawtext":[{"text":"§4[§cUAG§4]§r Clean up the chat."}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":""}]}
tellraw @s {"rawtext":[{"text":"§4[§cUAG§4]§r Done."}]}
playsound random.levelup @s