kill @s[type=item,name="Bedrock"]
kill @s[type=item,name="End Portal"]
kill @s[type=item,name="Command Block"]
kill @s[type=item,name="Chain Command Block"]
kill @s[type=item,name="Repeating Command Block"]
kill @s[type=item,name="Minecart with Command Block"]
kill @s[type=item,name="Barrier"]
kill @s[type=item,name="Structure Block"]
kill @s[type=item,name="Structure Void"]
kill @s[type=item,name="Jigsaw Block"]
kill @s[type=item,name="Allow"]
kill @s[type=item,name="Deny"]
kill @s[type=item,name="Light Block"]
kill @s[type=item,name="Border"]
kill @s[type=item,name="Compound Creator"]
kill @s[type=item,name="Frosted Ice"]
kill @s[type=item,name=""]
kill @s[type=item,name="Beehive"]
kill @s[type=item,name="Bee Nest"]
kill @s[type=item,name="岩盤"]
kill @s[type=item,name="エンドポータル"]
kill @s[type=item,name="コマンドブロック"]
kill @s[type=item,name="コマンドブロックのチェーン"]
kill @s[type=item,name="コマンドブロックの反復"]
#kill @s[type=item,name="コマンドブロック付きトロッコ"]
kill @s[type=item,name="バリアブロック"]
kill @s[type=item,name="ストラクチャー ブロック"]
kill @s[type=item,name="ストラクチャー ヴォイド"]
kill @s[type=item,name="ジグソー ブロック"]
kill @s[type=item,name="許可"]
kill @s[type=item,name="拒否"]
kill @s[type=item,name="ライト ブロック"]
kill @s[type=item,name="ボーダー"]
kill @s[type=item,name="Compound Creator"]
kill @s[type=item,name="氷霜"]
kill @s[type=item,name=""]
kill @s[type=item,name="Beehive"]
kill @s[type=item,name="Bee Nest"]
kill @s[type=item,name="tile.movingBlock.name"]
kill @s[type=item,name="§g§lBeehive Command"]
kill @s[type=item,name="§g§lBeeNest Command"]
kill @s[type=item,name="§g§lSpoofed BeeNest Command"]
kill @s[type=item,name="§g§lInvisible Beehive Command"]
kill @s[type=item,name="§g§lMovingBlock BeeNest Command"]
tag @s[type=item] add didCheck